# Generated by Django 4.0.5 on 2022-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueurs',
            name='type_j',
            field=models.CharField(blank=True, choices=[('PROFESSIONNEL', 'PRO'), ('PARTICULIER', 'PARTICULIER')], max_length=100),
        ),
    ]
