# Generated by Django 4.0.3 on 2022-06-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0002_alter_joueurs_type_j'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='photo_aut',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.auteurs'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='image_jeux',
            field=models.CharField(max_length=300),
        ),
    ]
