# Generated by Django 4.0.3 on 2022-06-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0004_alter_jeux_auteur_jeux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludo.auteurs'),
        ),
    ]
