# Generated by Django 4.0.3 on 2022-06-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0005_alter_jeux_auteur_jeux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteurs',
            name='prenom_aut',
        ),
    ]
