# Generated by Django 4.0.3 on 2022-06-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0006_remove_auteurs_prenom_aut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeux',
            name='editeur_jeux',
        ),
    ]
